### ISSUE TITLE
Failed to lookup model if it has special plural name

### ISSUE THREAD

**Issue by johncpang** [mediapolis/digitopia-admin#11]
I have a model called `Category`.  Everything I use the lookup field to search for the item, it failed.  It took me a long time before I notice something weird in the error message:

```
Unhandled error for request GET /api/Categorys/?filter[where][title][regexp]=/^Love/i: Error: There is no method to handle GET /Categorys/?filter[where][title][regexp]=/^Love/i
      at restUrlNotFound (/my_server/node_modules/strong-remoting/lib/rest-adapter.js:397:17)
      at Layer.handle [as handle_request] (/my_server/node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/my_server/node_modules/express/lib/router/index.js:317:13)
      at /my_server/node_modules/express/lib/router/index.js:284:7
      at Function.process_params (/my_server/node_modules/express/lib/router/index.js:335:12)
      at next (/my_server/node_modules/express/lib/router/index.js:275:10)
      at jsonParser (/my_server/node_modules/body-parser/lib/types/json.js:109:7)
      at Layer.handle [as handle_request] (/my_server/node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/my_server/node_modules/express/lib/router/index.js:317:13)
      at /my_server/node_modules/express/lib/router/index.js:284:7
      at Function.process_params (/my_server/node_modules/express/lib/router/index.js:335:12)
      at next (/my_server/node_modules/express/lib/router/index.js:275:10)
      at urlencodedParser (/my_server/node_modules/body-parser/lib/types/urlencoded.js:91:7)
      at Layer.handle [as handle_request] (/my_server/node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/my_server/node_modules/express/lib/router/index.js:317:13)
      at /my_server/node_modules/express/lib/router/index.js:284:7
```

It tried to call path `"/api/Categorys"` instead of `"/api/Categories"`.  I have defined plural in my JSON already.

```
{
  "name": "Category",
  "plural": "Categories",
  "base": "PersistedModel",
  ...
  "admin": {
    "defaultProperty": "title",
    "listProperties": [
      "title",
      "name"
    ],
    "viewProperties": [
      "title",
      "name"
    ],
    "editProperties": [
      "title",
      "name"
    ]
  },
  "properties": {
    "title": { "type": "string", "required": true },
    "name": { "type": "string", "required": true }
  },
  "validations": [],
  "relations": {
    "posts": {
      "type": "hasMany", "model": "Post", "foreignKey": "categoryId", "through": "PostCategory"
    }
  },
  "acls": [
    { "accessType": "*", "principalType": "ROLE", "principalId": "$everyone", "permission": "DENY" },
    { "accessType": "*", "principalType": "ROLE", "principalId": "admin", "permission": "ALLOW" },
    { "accessType": "READ", "principalType": "ROLE", "principalId": "$everyone", "permission": "ALLOW"}
  ],
}
```

**Comment by johncpang** [comment]
I found the code with problem and sent in a PR.  However, this fix requires that `plural` has been defined in the model JSON.  The best solution should obtain it via `app.models[model].pluralModelName` or similar.  However, I don't have time for that.

**Comment by johncpang** [comment]
My PR should work fine and also handle the case where no `plural` was set in model's JSON.  The code will fall back to original by appending an "s".  Please consider accepting the PR.  One of my friend was using your v0.0.9 and failed in lookup for "City" (Cities) and "Country" (Countries).  It took him over a month before I figure out he missed this fix.  So, this fix is critical.

**Comment by mediapolis** [comment]
Thanks.
