### ISSUE TITLE
Can't set headers after they are sent. error when user using back in browser 

### ISSUE THREAD

**Issue by johncpang** [mediapolis/digitopia-admin#7]
The admin server runs into `'Can't set headers after they are sent.'` error and crash itself.

```
Loopback version: 3.14.0
Web server listening at: http://localhost:5000
Browse your REST API at http://localhost:5000/explorer
_http_outgoing.js:356
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/project/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/project/node_modules/express/lib/response.js:170:12)
    at /project/node_modules/digitopia-admin/server/boot/admin.js:648:9
    at render (/project/node_modules/digitopia-admin/server/boot/admin.js:287:4)
    at /project/node_modules/digitopia-admin/server/boot/admin.js:631:4
    at /project/node_modules/digitopia-admin/node_modules/async/lib/async.js:726:13
    at /project/node_modules/digitopia-admin/node_modules/async/lib/async.js:52:16
    at /project/node_modules/digitopia-admin/node_modules/async/lib/async.js:269:32
    at /project/node_modules/digitopia-admin/node_modules/async/lib/async.js:44:16
    at /project/node_modules/digitopia-admin/node_modules/async/lib/async.js:723:17
    at /project/node_modules/digitopia-admin/node_modules/async/lib/async.js:167:37
    at getRoles (/project/node_modules/digitopia-admin/server/boot/admin.js:509:13)
    at /project/node_modules/digitopia-admin/node_modules/async/lib/async.js:718:13
    at iterate (/project/node_modules/digitopia-admin/node_modules/async/lib/async.js:262:13)
    at /project/node_modules/digitopia-admin/node_modules/async/lib/async.js:274:29
Exited with exit code 1
```

Here is the steps to reproduce:

1. Open the admin screen as usual.  Go to a model and look at item 2 (sample link below):
http://localhost:5000/admin/views/Model/2/view

2. Visit a non-exists item
http://localhost:5000/admin/views/Model/24/view

Observe that now the browser show 'not foun' (yes, a typo without 'd').

3. Now, press back in browser.  And the server crashed.

In real-life, here is scenario that will happen and crash:
1. Admin open the list of model.
2. End user delete an item via RESTful APIs
3. Admin tried to open that item from the (now cached) list.
4. Item not found.
5. Admin press back.

**Comment by mediapolis** [comment]
Crash on Error: Can't set headers after they are sent. should now be caught.

**Comment by johncpang** [comment]
wow. thanks a lot.
